[tool.commitizen]
name = "cz_customize"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true

[tool.commitizen.customize]
message_template = "{{change_type}} {{message}}{% if body %}\n\n{{body}}{% endif %}"
commit_parser = "^(?P<change_type>\\w+):\\s(?P<emoji>[^\\s]+)\\s(?P<message>.*)"

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = [
  { value = "feat: :sparkles:", name = "feat:      âœ¨ æ–°å¢åŠŸèƒ½ | Introducing new features" },
  { value = "fix: :bug:", name = "fix:       ğŸ› ä¿®å¤ç¼ºé™· | Fixing a bug" },
  { value = "init: :tada:", name = "init:      ğŸ‰ åˆå§‹é¡¹ç›® | Initial commit" },
  { value = "art: :art:", name = "art:       ğŸ¨ ç»“æ„æ”¹è¿› | Improving structure / format of the code" },
  { value = "docs: :memo:", name = "docs:      ğŸ“ æ–‡æ¡£æ›´æ–° | Documentation only changes" },
  { value = "style: :lipstick:", name = "style:     ğŸ’„ ä»£ç æ ¼å¼ | Updating the UI and style files" },
  { value = "refactor: :recycle:", name = "refactor:  â™»ï¸  ä»£ç é‡æ„ | A code change that neither fixes a bug nor adds a feature" },
  { value = "perf: :zap:", name = "perf:      âš¡ï¸ æ€§èƒ½æå‡ | A code change that improves performance" },
  { value = "test: :white_check_mark:", name = "test:      âœ… æµ‹è¯•ç›¸å…³ | Adding missing tests or correcting existing tests" },
  { value = "build: :package:", name = "build:     ğŸ“¦ï¸ æ„å»ºç›¸å…³ | Changes that affect the build system or external dependencies" },
  { value = "ci: :ferris_wheel:", name = "ci:        ğŸ¡ æŒç»­é›†æˆ | Changes to our CI configuration files and scripts" },
  { value = "revert: :hammer:", name = "revert:    ğŸ”¨ å›é€€ä»£ç  | Revert to a commit" },
  { value = "chore: :rewind:", name = "chore:     âªï¸ å…¶ä»–ä¿®æ”¹ | Other changes that do not modify src or test files" },
]
message = "é€‰æ‹©ä½ æ­£åœ¨æäº¤çš„æ”¹åŠ¨ç±»å‹:"

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "å¡«å†™ç®€çŸ­ç²¾ç‚¼çš„å˜æ›´æè¿°:"

[[tool.commitizen.customize.questions]]
type = "input"
name = "body"
multiline = true
message = "[å¯é€‰]å¡«å†™æ›´åŠ è¯¦ç»†çš„å˜æ›´æè¿°:"
